import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/index.module.scss";
import Loading from "../components/Loading";
import Header from "../components/Header";
import { useState, useEffect } from "react";
import { AnimatePresence, motion } from "framer-motion";
import Image from "next/image";

const Home: NextPage = () => {
  const [LoadingDone, setLoadingDone] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setLoadingDone(true);
    }, 1000);
  }, []);
  const letterVariants = {
    initial: {
      y: 450,
    },
    animate: {
      y: 0,
      transition: {
        duration: 1.2,
        ease: [0.165, 0.84, 0.44, 1],
      },
    },
  };
  const lettersContainer = {
    initial: {},
    animate: {
      transition: {
        delayChildren: 1.5,
        staggerChildren: 0.1,
      },
    },
  };
  const imageVariants = {
    initial: { scale: 1.5, x: "-50%" },
    animate: {
      scale: 1,
      x: "-50%",
      transition: {
        ease: [0.165, 0.84, 0.44, 1],
        duration: 1.5,
        delay: 1.2,
      },
    },
  };
  const info = {
    initial: {
      y: "5vw",
    },
    animate: {
      y: 0,
      transition: {
        ease: [0.165, 0.84, 0.44, 1],
        duration: 1.2,
        delay: 1.6,
      },
    },
  };
  const lowerInfo = {
    initial: {
      y: "5vw",
    },
    animate: {
      y: 0,
      transition: {
        ease: [0.165, 0.84, 0.44, 1],
        duration: 1.2,
        delay: 1.8,
      },
    },
  };

  const button = {
    initial: {
      opacity: 0,
    },
    animate: {
      opacity: 1,
      transition: {
        ease: [0.165, 0.84, 0.44, 1],
        delay: 2.2,
        duration: 2,
      },
    },
  };
  return (
    <div className={styles.pageContainer}>
      <Head>
        <title>BRAND &reg;</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.container}>
        <section className={styles.productInfo}>
          <div className={styles.topLine}>
            <motion.span
              className={styles.text}
              variants={info}
              initial={"initial"}
              animate={"animate"}
            >
              The Duffle in premium
            </motion.span>
          </div>
          <div className={styles.bottomLine}>
            <motion.span
              className={styles.text}
              variants={lowerInfo}
              initial={"initial"}
              animate={"animate"}
            >
              black Leather.
            </motion.span>
          </div>
          <motion.button
            className={styles.moreProducts}
            variants={button}
            initial={"initial"}
            animate={"animate"}
          >
            <span className={styles.text}>Discover more products</span>
            <Image src={"/whiteArrow.png"} width={"32"} height={"32"} />
          </motion.button>
        </section>
        <motion.div
          className={styles.mainImageContainer}
          variants={imageVariants}
          animate={"animate"}
          initial={"initial"}
        >
          <Image src={"/image1.png"} width={"1380"} height={"899"} />
        </motion.div>
        <motion.div
          className={styles.letterRevealContainer}
          variants={lettersContainer}
          animate={"animate"}
          initial={"initial"}
        >
          {"BRAND®".split("").map((letter, index) => (
            <motion.span
              key={index}
              className={`${styles.letter} ${
                index == 5 ? styles.reserved : undefined
              }`}
              variants={letterVariants}
            >
              {letter}
            </motion.span>
          ))}
        </motion.div>
      </main>
      <AnimatePresence exitBeforeEnter>
        {!LoadingDone && <Loading key={"loading"} />}
      </AnimatePresence>
    </div>
  );
};

export default Home;
